export const S = {
  app: {
    minHeight: '100vh',
    background: '#0d1117',
    display: 'flex',
    fontFamily: "'DM Sans', system-ui, sans-serif",
  },
  shell: {
    display: 'grid',
    gridTemplateColumns: '200px 1fr',
    width: '100%',
    minHeight: '100vh',
  },
  sidebar: {
    background: '#090d14',
    borderRight: '1px solid #1e2537',
    padding: '20px 0',
    display: 'flex',
    flexDirection: 'column',
    position: 'sticky',
    top: 0,
    height: '100vh',
    overflowY: 'auto',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '0 16px 18px',
    borderBottom: '1px solid #1e2537',
    marginBottom: 8,
  },
  logoMark: {
    width: 32,
    height: 32,
    background: 'linear-gradient(135deg,#1d4ed8,#60a5fa)',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 800,
    fontSize: 16,
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 16px',
    fontSize: 13,
    cursor: 'pointer',
    color: '#475569',
    background: 'none',
    border: 'none',
    width: '100%',
    textAlign: 'left',
    transition: 'all 0.15s',
  },
  navActive: {
    background: '#0f1a2e',
    color: '#60a5fa',
    borderRight: '2px solid #60a5fa',
  },
  main: {
    padding: '28px',
    overflowY: 'auto',
    minWidth: 0,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: '#e2e8f0',
    margin: 0,
    letterSpacing: '-0.03em',
  },
  panel: {
    background: '#0d1520',
    border: '1px solid #1e2537',
    borderRadius: 14,
    padding: '18px',
  },
  tabs: {
    display: 'flex',
    border: '1px solid #1e2537',
    borderRadius: 10,
    overflow: 'hidden',
  },
  tab: {
    flex: 1,
    padding: '8px 0',
    fontSize: 12,
    cursor: 'pointer',
    color: '#64748b',
    background: '#090d14',
    border: 'none',
    transition: 'all 0.15s',
  },
  tabActive: {
    background: '#151b27',
    color: '#e2e8f0',
    fontWeight: 600,
  },
  uploadZone: {
    border: '1px dashed #1e2537',
    borderRadius: 12,
    padding: '28px 16px',
    textAlign: 'center',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    transition: 'border-color 0.15s',
  },
  catGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,1fr)',
    gap: 6,
    marginTop: 4,
  },
  catBtn: {
    border: '1px solid #1e2537',
    borderRadius: 8,
    padding: '7px 4px',
    textAlign: 'center',
    cursor: 'pointer',
    fontSize: 11,
    color: '#64748b',
    background: '#090d14',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
    transition: 'all 0.15s',
  },
  catBtnActive: {
    background: '#0f1a2e',
    border: '1px solid #1d4ed8',
    color: '#93c5fd',
  },
  input: {
    fontSize: 13,
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #1e2537',
    background: '#090d14',
    color: '#e2e8f0',
    width: '100%',
    outline: 'none',
  },
  lbl: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: 500,
    marginBottom: 4,
    display: 'block',
  },
  fg: { display: 'flex', flexDirection: 'column' },
  btnPrimary: {
    padding: '9px 16px',
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 9,
    background: '#1d4ed8',
    border: '1px solid #2563eb',
    color: '#fff',
    cursor: 'pointer',
    transition: 'opacity 0.15s',
    width: '100%',
  },
  btnGhost: {
    padding: '8px 14px',
    fontSize: 12,
    borderRadius: 9,
    background: '#151b27',
    border: '1px solid #1e2537',
    color: '#94a3b8',
    cursor: 'pointer',
  },
  btnSmall: {
    padding: '5px 12px',
    fontSize: 12,
    borderRadius: 7,
    background: '#1d4ed8',
    border: '1px solid #2563eb',
    color: '#fff',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  typeToggle: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    border: '1px solid #1e2537',
    borderRadius: 9,
    overflow: 'hidden',
  },
  typeBtn: {
    padding: '8px',
    fontSize: 12,
    cursor: 'pointer',
    color: '#64748b',
    background: '#090d14',
    border: 'none',
    fontWeight: 500,
    transition: 'all 0.15s',
  },
  typeBtnExpense: { background: '#2a0f0f', color: '#f87171' },
  typeBtnIncome:  { background: '#0f2a1a', color: '#4ade80' },
  successBanner: {
    background: '#0f2a1a',
    border: '1px solid #1a4a2a',
    borderRadius: 8,
    padding: '9px 12px',
    fontSize: 12,
    color: '#4ade80',
  },
  monthInput: {
    background: '#151b27',
    border: '1px solid #1e2537',
    borderRadius: 8,
    padding: '5px 10px',
    color: '#e2e8f0',
    fontSize: 12,
    fontFamily: 'inherit',
    outline: 'none',
    cursor: 'pointer',
    colorScheme: 'dark', // helpful for native input
    userSelect: 'none',
    WebkitUserSelect: 'none',
  },
}
